export const PODCAST_GENRES = [
  "News & Current Affairs",
  "Business & Finance",
  "Education & Learning",
  "Technology",
  "Health & Wellness",
  "Entertainment",
  "Society & Culture",
  "Sports",
  "Arts & Creativity",
  "Religion & Spirituality",
  "Fiction & Storytelling",
  "Kids & Family",
  "Travel",
  "Science",
  "Interview & Talk Shows",
  "Pets & Animals",
  "Real Estate",
  "Fashion & Beauty",
  "Automobile",
  "Gaming",
  "Music",
  "General",
];
